name: austrian-flood-monitoring-db

services:
  db:
    container_name: flood-monitoring-db
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # Here we can add a service in the future to setup the database with the schema and example data
  db-setup:
    container_name: flood-monitoring-db-setup
    image: node:20-slim
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./server:/app
    working_dir: /app
    entrypoint:
      ["sh", "-c", "apt-get update && apt-get install -y openssl && npm install && npx prisma migrate reset --force && npm run seed"]
    environment:
      DATABASE_URL: ${DATABASE_URL}
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  db-data:
